# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: FabWorks
email: james.wade2@uky.edu
description: > # this means to ignore newlines until "baseurl:"
  FabWorks is a lab at the School of Arts and Visual Studies at the University of Kentucky
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://fabworks.github.io" # the base hostname & protocol for your site


# Build settings
markdown: kramdown
